name: Process java files

on:
  push:
    paths:
      - 'java_files/**/*.java'
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: List repository files
        run: |
          echo "Files in the workspace:"
          ls -R

      - name: Verify current directory
        run: pwd

      - name: Ensure file permissions
        run: chmod +r main.py

      - name: Verify Python script
        run: |
          if [ -f main.py ]; then
            echo "main.py exists!"
          else
            echo "main.py not found!"
            exit 1
          fi

      - name: Run Python script
        run: python main.py || exit 1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Debugging file paths
        run: find java_files/ -type f -name "*.java"

      - name: Run Python script on .java files
        run: |
          find java_files/ -type f -name "*.java" > file_list.txt
          python main.py file_list.txt

      - name: Upload results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: processed-java-files
          path: 'updated_files/**/*'
