name: Process Java Code

on:
  push:
    paths:
      - 'java_files/**/*.java'  # Trigger on any .java file within java_files directory

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Correct usage of a GitHub Action

      - name: Set up Python
        uses: actions/setup-python@v4  # Correct usage of a GitHub Action
        with:
          python-version: '3.9'

      - name: Download Python script
        run: |
          curl -H "Authorization: token ${{ secrets.GH_PAT }}" -o main.py https://raw.githubusercontent.com/Buhnana/FFP-Replacer/main/main.py

      - name: Verify Python script
        run: cat main.py

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          echo "No dependencies required" > requirements.txt
          pip install -r requirements.txt || true

      - name: Debugging File Paths
        run: find java_files/ -type f -name "*.java"

      - name: Run Python script on .java files
        run: python /home/zealot/Documents/MCHELI-O 1.12.2 SRC/FFP-Replacer-Flans/main.py

      - name: Upload results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4  # Correct usage of a GitHub Action
        with:
          name: processed-java-files
          path: 'updated_files/**/*'  # Upload the files from the output directory
